languageCode = "en-us"
title = "Orquestra"
theme = "whisper"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

RelativeURLs=true
baseURL="https://www.orquestra.io/docs/"
# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[params]
  google_analytics_id=""
  homepage_button_link1 = '/tutorials/hello-workflow/'
  homepage_button_text1 = 'Start the tutorial'
  homepage_button_link2 = '/getting-started/platform'
  homepage_button_text2 = 'Learn More'
  homepage_intro = 'Orquestra is a platform for building repeatable workflows, orchestrated by a quantum engine that systematically organizes experiment data and resources.'
  homepage_image = '/images/terminal.gif'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Orquestra is a platform for building repeatable workflows, orchestrated by a quantum engine that systematically organizes experiment data and resources."
    meta_og_title = "Orquestra Docs"
    meta_og_type = "website"
    meta_og_url = "http://orquestra.io/docs/"
    meta_og_image = "https://raw.githubusercontent.com/zapatacomputing/orquestra-docs/master/v1/static/orquestra-logo.svg"
    meta_og_description = "Orquestra is a platform for building repeatable workflows, orchestrated by a quantum engine that systematically organizes experiment data and resources."
    meta_twitter_card = "summary"
    meta_twitter_site = "@ZapataComputing"
    meta_twitter_creator = "@ZapataComputing"

  [params.logo]
      mobile = "/orquestra-logo-mobile.svg"
      standard  = "/orquestra-logo.svg"

[markup.goldmark.renderer]
unsafe= true
